#!/usr/bin/env node
/**
 * Gallery Image Scanner
 * Scans /public/img/gallery and generates src/data/galleryImages.ts
 * Prefers .webp files when available, falls back to .jpg/.jpeg
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const GALLERY_DIR = path.join(ROOT, "public", "img", "gallery");
const OUTPUT_FILE = path.join(ROOT, "src", "data", "galleryImages.ts");

// Supported image extensions (in order of preference)
const EXTENSIONS = [".webp", ".jpg", ".jpeg", ".png"];

function scanGallery() {
  if (!fs.existsSync(GALLERY_DIR)) {
    console.error(`Gallery directory not found: ${GALLERY_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(GALLERY_DIR);

  // Group files by base name (number)
  const imageMap = new Map();

  for (const file of files) {
    const ext = path.extname(file).toLowerCase();
    if (!EXTENSIONS.includes(ext)) continue;

    const baseName = path.basename(file, ext);

    // Skip if we already have a preferred format
    if (imageMap.has(baseName)) {
      const existingExt = path.extname(imageMap.get(baseName)).toLowerCase();
      const existingPriority = EXTENSIONS.indexOf(existingExt);
      const newPriority = EXTENSIONS.indexOf(ext);

      // Only replace if new format has higher priority (lower index)
      if (newPriority < existingPriority) {
        imageMap.set(baseName, file);
      }
    } else {
      imageMap.set(baseName, file);
    }
  }

  // Sort by numeric value for consistent ordering
  const sortedImages = Array.from(imageMap.entries())
    .sort((a, b) => {
      const numA = parseInt(a[0], 10) || 0;
      const numB = parseInt(b[0], 10) || 0;
      return numA - numB;
    })
    .map(([_, filename]) => `/img/gallery/${filename}`);

  return sortedImages;
}

function generateTypeScript(images) {
  const output = `/**
 * Gallery Images
 * Auto-generated by scripts/generate-gallery.mjs
 * Run: npm run gallery:generate
 *
 * DO NOT EDIT MANUALLY
 */

export const galleryImages: string[] = [
${images.map((img) => `  "${img}",`).join("\n")}
];

export default galleryImages;
`;

  // Ensure data directory exists
  const dataDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Generated ${OUTPUT_FILE}`);
  console.log(`Found ${images.length} images`);
}

// Run
const images = scanGallery();
generateTypeScript(images);
